# Generated by Django 3.1.7 on 2021-03-08 16:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=1024, verbose_name='Adres')),
                ('zip_code', models.CharField(max_length=12, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=1024, verbose_name='Miejscowość')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('type', models.CharField(choices=[('ZOL', 'Zakład opiekuńczo-leczniczy'), ('OR', 'Oddział Rehabilitacji'), ('S', 'Sanatorium'), ('DPS', 'Dom Pomocy Społecznej'), ('DOP', 'Długoterminowa opieka prywatna'), ('KOP', 'Krótkoterminowa opieka prywatna')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_number', models.IntegerField()),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('premises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.premises')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('room', models.ManyToManyField(to='main.Room')),
            ],
        ),
    ]
