# Generated by Django 3.1.7 on 2021-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210309_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
