# Generated by Django 3.1.7 on 2021-03-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210311_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='premises',
        ),
        migrations.AddField(
            model_name='review',
            name='premise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.premises'),
            preserve_default=False,
        ),
    ]
