# Generated by Django 3.1.7 on 2021-03-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210316_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='premise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.premises'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='reservations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.reservation'),
        ),
    ]
