# Generated by Django 3.1.7 on 2021-03-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210317_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_reserved',
        ),
    ]
