# Generated by Django 3.1.7 on 2021-03-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_room_is_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
    ]
