# Generated by Django 3.1.7 on 2021-03-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210320_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reservations',
            new_name='reservation',
        ),
    ]
